import fs from 'node:fs';
import path from 'node:path';
import crypto from 'node:crypto';

/**
 * Database handle. Works on PostgreSQL through either driver:
 *  - Supabase (or any Postgres) via the `postgres` package when DATABASE_URL is set
 *  - PGlite (Postgres compiled to WebAssembly) for local development and tests
 * Queries use `?` placeholders; they're converted to $1, $2… here.
 */
export interface DB {
  query(sql: string, params: unknown[]): Promise<{ rows: any[]; rowCount: number }>;
  /** Runs a multi-statement script without parameters (schema). */
  exec(sql: string): Promise<void>;
  transaction<T>(fn: (db: DB) => Promise<T>): Promise<T>;
  close(): Promise<void>;
  inTransaction?: boolean;
}
export type Params = unknown[];

const SCHEMA = `-- SQLite-compatible helpers so queries read the same on every database.
CREATE OR REPLACE FUNCTION datetime(t text, modifier text DEFAULT NULL) RETURNS text LANGUAGE sql STABLE AS $fn$
  SELECT CASE WHEN t IS NULL THEN NULL ELSE to_char(
    (CASE WHEN lower(t) = 'now' THEN (now() AT TIME ZONE 'utc') ELSE t::timestamp END) + COALESCE(modifier, '0 seconds')::interval,
    'YYYY-MM-DD HH24:MI:SS') END
$fn$;
CREATE OR REPLACE FUNCTION julianday(t text) RETURNS double precision LANGUAGE sql STABLE AS $fn$
  SELECT CASE WHEN t IS NULL THEN NULL ELSE
    extract(epoch FROM (CASE WHEN lower(t) = 'now' THEN (now() AT TIME ZONE 'utc') ELSE t::timestamp END)) / 86400.0 + 2440587.5 END
$fn$;


CREATE TABLE IF NOT EXISTS roles (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  key TEXT UNIQUE,
  name TEXT NOT NULL,
  permissions TEXT NOT NULL DEFAULT '[]',
  is_system INTEGER NOT NULL DEFAULT 0,
  created_at TEXT NOT NULL DEFAULT (datetime('now'))
);

CREATE TABLE IF NOT EXISTS users (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name TEXT NOT NULL,
  email TEXT NOT NULL,
  phone TEXT,
  password_hash TEXT NOT NULL,
  role_id INTEGER NOT NULL REFERENCES roles(id),
  status TEXT NOT NULL DEFAULT 'active',
  must_change_password INTEGER NOT NULL DEFAULT 0,
  failed_attempts INTEGER NOT NULL DEFAULT 0,
  locked_until TEXT,
  created_at TEXT NOT NULL DEFAULT (datetime('now')),
  last_login TEXT,
  last_activity TEXT
);

CREATE TABLE IF NOT EXISTS sessions (
  id TEXT PRIMARY KEY,
  user_id INTEGER NOT NULL REFERENCES users(id) ON DELETE CASCADE,
  remember INTEGER NOT NULL DEFAULT 0,
  created_at TEXT NOT NULL DEFAULT (datetime('now')),
  last_seen TEXT NOT NULL DEFAULT (datetime('now')),
  expires_at TEXT NOT NULL,
  ip TEXT,
  user_agent TEXT
);

CREATE TABLE IF NOT EXISTS password_resets (
  token_hash TEXT PRIMARY KEY,
  user_id INTEGER NOT NULL REFERENCES users(id) ON DELETE CASCADE,
  expires_at TEXT NOT NULL,
  used_at TEXT,
  created_by INTEGER REFERENCES users(id),
  created_at TEXT NOT NULL DEFAULT (datetime('now'))
);

CREATE TABLE IF NOT EXISTS settings (
  key TEXT PRIMARY KEY,
  value TEXT NOT NULL
);

CREATE TABLE IF NOT EXISTS developers (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name TEXT NOT NULL,
  active INTEGER NOT NULL DEFAULT 1,
  created_at TEXT NOT NULL DEFAULT (datetime('now'))
);

CREATE TABLE IF NOT EXISTS projects (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name TEXT NOT NULL,
  developer_id INTEGER REFERENCES developers(id) ON DELETE SET NULL,
  location TEXT,
  active INTEGER NOT NULL DEFAULT 1,
  created_at TEXT NOT NULL DEFAULT (datetime('now'))
);

CREATE TABLE IF NOT EXISTS master_values (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  category TEXT NOT NULL,
  value TEXT NOT NULL,
  sort INTEGER NOT NULL DEFAULT 0,
  active INTEGER NOT NULL DEFAULT 1
);

CREATE TABLE IF NOT EXISTS tags (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name TEXT NOT NULL,
  color TEXT NOT NULL DEFAULT 'gray'
);

CREATE TABLE IF NOT EXISTS taggings (
  tag_id INTEGER NOT NULL REFERENCES tags(id) ON DELETE CASCADE,
  entity_type TEXT NOT NULL,
  entity_id INTEGER NOT NULL,
  PRIMARY KEY (tag_id, entity_type, entity_id)
);
CREATE INDEX IF NOT EXISTS idx_taggings_entity ON taggings(entity_type, entity_id);

CREATE TABLE IF NOT EXISTS owners (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name TEXT NOT NULL,
  name_ar TEXT,
  primary_phone TEXT,
  primary_phone_norm TEXT,
  secondary_phone TEXT,
  secondary_phone_norm TEXT,
  whatsapp TEXT,
  whatsapp_norm TEXT,
  email TEXT,
  address TEXT,
  assigned_user_id INTEGER REFERENCES users(id) ON DELETE SET NULL,
  source TEXT,
  status TEXT NOT NULL DEFAULT 'Active',
  last_contacted TEXT,
  created_by INTEGER REFERENCES users(id) ON DELETE SET NULL,
  created_at TEXT NOT NULL DEFAULT (datetime('now')),
  updated_at TEXT NOT NULL DEFAULT (datetime('now')),
  archived_at TEXT
);
CREATE INDEX IF NOT EXISTS idx_owners_phone ON owners(primary_phone_norm);
CREATE INDEX IF NOT EXISTS idx_owners_phone2 ON owners(secondary_phone_norm);
CREATE INDEX IF NOT EXISTS idx_owners_wa ON owners(whatsapp_norm);
CREATE INDEX IF NOT EXISTS idx_owners_name ON owners (lower(name));

CREATE TABLE IF NOT EXISTS units (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  owner_id INTEGER REFERENCES owners(id) ON DELETE SET NULL,
  developer_id INTEGER REFERENCES developers(id) ON DELETE SET NULL,
  project_id INTEGER REFERENCES projects(id) ON DELETE SET NULL,
  phase TEXT,
  unit_number TEXT,
  unit_number_norm TEXT,
  property_type TEXT,
  bua DOUBLE PRECISION,
  land_area DOUBLE PRECISION,
  bedrooms INTEGER,
  bathrooms INTEGER,
  floors INTEGER,
  finishing TEXT,
  furnished TEXT,
  view TEXT,
  location TEXT,
  delivery TEXT,
  asking_price DOUBLE PRECISION,
  original_price DOUBLE PRECISION,
  paid_amount DOUBLE PRECISION,
  remaining_amount DOUBLE PRECISION,
  maintenance DOUBLE PRECISION,
  payment_notes TEXT,
  status TEXT NOT NULL DEFAULT 'Available',
  assigned_user_id INTEGER REFERENCES users(id) ON DELETE SET NULL,
  source TEXT,
  last_verified TEXT,
  verification_notified_level TEXT,
  created_by INTEGER REFERENCES users(id) ON DELETE SET NULL,
  created_at TEXT NOT NULL DEFAULT (datetime('now')),
  updated_at TEXT NOT NULL DEFAULT (datetime('now')),
  archived_at TEXT
);
CREATE INDEX IF NOT EXISTS idx_units_owner ON units(owner_id);
CREATE INDEX IF NOT EXISTS idx_units_project ON units(project_id, unit_number_norm);
CREATE INDEX IF NOT EXISTS idx_units_status ON units(status);

CREATE TABLE IF NOT EXISTS requirements (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  client_name TEXT NOT NULL,
  phone TEXT,
  phone_norm TEXT,
  whatsapp TEXT,
  assigned_user_id INTEGER REFERENCES users(id) ON DELETE SET NULL,
  developer_id INTEGER REFERENCES developers(id) ON DELETE SET NULL,
  preferred_project_ids TEXT NOT NULL DEFAULT '[]',
  property_types TEXT NOT NULL DEFAULT '[]',
  min_bua DOUBLE PRECISION,
  max_bua DOUBLE PRECISION,
  min_bedrooms INTEGER,
  min_price DOUBLE PRECISION,
  max_price DOUBLE PRECISION,
  finishing TEXT,
  delivery_preference TEXT,
  priority TEXT NOT NULL DEFAULT 'Medium',
  status TEXT NOT NULL DEFAULT 'Active',
  created_by INTEGER REFERENCES users(id) ON DELETE SET NULL,
  created_at TEXT NOT NULL DEFAULT (datetime('now')),
  updated_at TEXT NOT NULL DEFAULT (datetime('now')),
  archived_at TEXT
);
CREATE INDEX IF NOT EXISTS idx_req_phone ON requirements(phone_norm);

CREATE TABLE IF NOT EXISTS requirement_exclusions (
  requirement_id INTEGER NOT NULL REFERENCES requirements(id) ON DELETE CASCADE,
  unit_id INTEGER NOT NULL REFERENCES units(id) ON DELETE CASCADE,
  created_by INTEGER REFERENCES users(id) ON DELETE SET NULL,
  created_at TEXT NOT NULL DEFAULT (datetime('now')),
  PRIMARY KEY (requirement_id, unit_id)
);

CREATE TABLE IF NOT EXISTS requirement_match_seen (
  requirement_id INTEGER NOT NULL REFERENCES requirements(id) ON DELETE CASCADE,
  unit_id INTEGER NOT NULL REFERENCES units(id) ON DELETE CASCADE,
  PRIMARY KEY (requirement_id, unit_id)
);

CREATE TABLE IF NOT EXISTS offer_templates (
  key TEXT PRIMARY KEY,
  name TEXT NOT NULL,
  description TEXT,
  header TEXT NOT NULL DEFAULT '',
  unit_block TEXT NOT NULL DEFAULT '',
  separator TEXT NOT NULL DEFAULT '',
  footer TEXT NOT NULL DEFAULT '',
  include_owner INTEGER NOT NULL DEFAULT 0,
  updated_at TEXT NOT NULL DEFAULT (datetime('now'))
);

CREATE TABLE IF NOT EXISTS offers (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  created_by INTEGER REFERENCES users(id) ON DELETE SET NULL,
  client_name TEXT,
  requirement_id INTEGER REFERENCES requirements(id) ON DELETE SET NULL,
  template TEXT NOT NULL,
  content TEXT NOT NULL,
  created_at TEXT NOT NULL DEFAULT (datetime('now'))
);

CREATE TABLE IF NOT EXISTS offer_units (
  offer_id INTEGER NOT NULL REFERENCES offers(id) ON DELETE CASCADE,
  unit_id INTEGER NOT NULL REFERENCES units(id) ON DELETE CASCADE,
  position INTEGER NOT NULL DEFAULT 0,
  PRIMARY KEY (offer_id, unit_id)
);
CREATE INDEX IF NOT EXISTS idx_offer_units_unit ON offer_units(unit_id);

CREATE TABLE IF NOT EXISTS notes (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  entity_type TEXT NOT NULL,
  entity_id INTEGER NOT NULL,
  content TEXT NOT NULL,
  author_id INTEGER REFERENCES users(id) ON DELETE SET NULL,
  created_at TEXT NOT NULL DEFAULT (datetime('now'))
);
CREATE INDEX IF NOT EXISTS idx_notes_entity ON notes(entity_type, entity_id);

CREATE TABLE IF NOT EXISTS files (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  entity_type TEXT NOT NULL,
  entity_id INTEGER NOT NULL,
  category TEXT NOT NULL DEFAULT 'document',
  original_name TEXT NOT NULL,
  stored_name TEXT NOT NULL,
  mime TEXT,
  size INTEGER,
  uploaded_by INTEGER REFERENCES users(id) ON DELETE SET NULL,
  created_at TEXT NOT NULL DEFAULT (datetime('now'))
);
CREATE INDEX IF NOT EXISTS idx_files_entity ON files(entity_type, entity_id);

CREATE TABLE IF NOT EXISTS activity (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id INTEGER REFERENCES users(id) ON DELETE SET NULL,
  action TEXT NOT NULL,
  entity_type TEXT,
  entity_id INTEGER,
  entity_label TEXT,
  field TEXT,
  old_value TEXT,
  new_value TEXT,
  message TEXT,
  created_at TEXT NOT NULL DEFAULT (datetime('now'))
);
CREATE INDEX IF NOT EXISTS idx_activity_entity ON activity(entity_type, entity_id);
CREATE INDEX IF NOT EXISTS idx_activity_created ON activity(created_at);

CREATE TABLE IF NOT EXISTS notifications (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id INTEGER NOT NULL REFERENCES users(id) ON DELETE CASCADE,
  type TEXT NOT NULL,
  message TEXT NOT NULL,
  link TEXT,
  read_at TEXT,
  created_at TEXT NOT NULL DEFAULT (datetime('now'))
);
CREATE INDEX IF NOT EXISTS idx_notifications_user ON notifications(user_id, read_at);

CREATE TABLE IF NOT EXISTS saved_views (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  entity TEXT NOT NULL DEFAULT 'units',
  name TEXT NOT NULL,
  user_id INTEGER REFERENCES users(id) ON DELETE CASCADE,
  shared INTEGER NOT NULL DEFAULT 0,
  config TEXT NOT NULL,
  created_at TEXT NOT NULL DEFAULT (datetime('now')),
  updated_at TEXT NOT NULL DEFAULT (datetime('now'))
);

CREATE TABLE IF NOT EXISTS imports (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id INTEGER REFERENCES users(id) ON DELETE SET NULL,
  filename TEXT NOT NULL,
  kind TEXT NOT NULL DEFAULT 'inventory',
  status TEXT NOT NULL DEFAULT 'uploaded',
  headers TEXT NOT NULL DEFAULT '[]',
  rows TEXT NOT NULL DEFAULT '[]',
  mapping TEXT,
  options TEXT,
  summary TEXT,
  result TEXT,
  created_at TEXT NOT NULL DEFAULT (datetime('now')),
  completed_at TEXT
);

CREATE UNIQUE INDEX IF NOT EXISTS uq_roles_name ON roles (lower(name));
CREATE UNIQUE INDEX IF NOT EXISTS uq_users_email ON users (lower(email));
CREATE UNIQUE INDEX IF NOT EXISTS uq_developers_name ON developers (lower(name));
CREATE UNIQUE INDEX IF NOT EXISTS uq_projects_name ON projects (lower(name));
CREATE UNIQUE INDEX IF NOT EXISTS uq_tags_name ON tags (lower(name));
CREATE UNIQUE INDEX IF NOT EXISTS uq_master_values ON master_values (category, lower(value));
`;

function toPg(sql: string): string {
  // Replace ? placeholders outside string literals with $1, $2, …
  let n = 0;
  let out = '';
  let quote = false;
  for (const ch of sql) {
    if (ch === "'") quote = !quote;
    out += !quote && ch === '?' ? `$${++n}` : ch;
  }
  return out;
}

function args(params: Params): unknown[] {
  return params.map((v) => (v === undefined ? null : typeof v === 'boolean' ? (v ? 1 : 0) : v));
}

async function pglite(dir: string | null): Promise<DB> {
  const { PGlite } = await import('@electric-sql/pglite');
  if (dir) fs.mkdirSync(dir, { recursive: true });
  const pg = new PGlite(dir ?? undefined, { parsers: { 20: Number, 1700: Number } });
  const wrap = (q: { query: typeof pg.query }, inTx: boolean): DB => ({
    inTransaction: inTx,
    async query(sql, params) {
      const r = await q.query(sql, params as any[]);
      return { rows: r.rows as any[], rowCount: r.affectedRows ?? r.rows.length };
    },
    exec: async (text) => {
      await (inTx ? (q as any) : pg).exec(text);
    },
    transaction: (fn) => (inTx ? fn(wrap(q, true)) : pg.transaction((t) => fn(wrap(t as any, true)))),
    close: () => pg.close(),
  });
  return wrap(pg, false);
}

async function postgresUrl(url: string): Promise<DB> {
  const { default: postgres } = await import('postgres');
  const num = { to: 0, from: [20, 1700], serialize: (x: number) => String(x), parse: (x: string) => Number(x) };
  // prepare:false works with Supabase's transaction pooler (port 6543), which serverless functions should use.
  const sql = postgres(url, { prepare: false, max: process.env.VERCEL ? 1 : 10, idle_timeout: 20, types: { num } as any, onnotice: () => undefined });
  const wrap = (q: any, inTx: boolean): DB => ({
    inTransaction: inTx,
    async query(text, params) {
      const r = await q.unsafe(text, params);
      return { rows: [...r], rowCount: r.count ?? r.length };
    },
    exec: async (text) => {
      await q.unsafe(text).simple(); // simple protocol allows several statements
    },
    transaction: (fn) => (inTx ? fn(wrap(q, true)) : sql.begin((t: any) => fn(wrap(t, true))) as Promise<any>),
    close: () => sql.end(),
  });
  return wrap(sql, false);
}

/**
 * Opens the database and applies the schema.
 *  - "postgres://…" / "postgresql://…" → Supabase or another Postgres server
 *  - ":memory:" → throwaway PGlite database (tests)
 *  - anything else → a PGlite data directory on disk (local development)
 */
export async function openDb(target: string): Promise<DB> {
  const db = /^postgres(ql)?:\/\//.test(target) ? await postgresUrl(target) : await pglite(target === ':memory:' ? null : path.resolve(target));
  await migrate(db);
  return db;
}

const SCHEMA_VERSION = crypto.createHash('sha256').update(SCHEMA).digest('hex').slice(0, 16);

/**
 * Applies the schema once per version. Serverless instances may start at the same time, so the
 * work runs in a transaction behind an advisory lock and is skipped when the version matches.
 */
async function migrate(db: DB) {
  const current = async (d: DB) =>
    (await d.query("SELECT to_regclass('schema_meta') IS NOT NULL AS ok", [])).rows[0]?.ok
      ? (await d.query('SELECT version FROM schema_meta LIMIT 1', [])).rows[0]?.version
      : null;
  if ((await current(db)) === SCHEMA_VERSION) return;
  await db.transaction(async (t) => {
    await t.query('SELECT pg_advisory_xact_lock(727274)', []);
    if ((await current(t)) === SCHEMA_VERSION) return;
    await ensureNocase(t);
    await t.exec(SCHEMA);
    // Supabase exposes the public schema through its REST API; with row-level security on and no
    // policies, only the app's own connection (the table owner) can read or write the data.
    await t.exec(
      (await t.query("SELECT tablename FROM pg_tables WHERE schemaname = current_schema()", [])).rows
        .map((r) => `ALTER TABLE "${r.tablename}" ENABLE ROW LEVEL SECURITY;`)
        .join('\n'),
    );
    await t.exec('CREATE TABLE IF NOT EXISTS schema_meta (version TEXT NOT NULL); ALTER TABLE schema_meta ENABLE ROW LEVEL SECURITY; DELETE FROM schema_meta;');
    await t.query('INSERT INTO schema_meta (version) VALUES ($1)', [SCHEMA_VERSION]);
  });
}

/**
 * Case-insensitive comparison and sorting ("Mivida" = "MIVIDA"), used in queries as COLLATE NOCASE.
 * Newer ICU understands "und-u-ks-level2"; some builds only the legacy "@colStrength=secondary".
 */
async function ensureNocase(db: DB) {
  for (const locale of ['und-u-ks-level2', '@colStrength=secondary']) {
    await db.query(`CREATE COLLATION IF NOT EXISTS nocase (provider = icu, locale = '${locale}', deterministic = false)`, []);
    const ok = (await db.query("SELECT 'Mivida' = 'MIVIDA' COLLATE nocase AS ok", [])).rows[0]?.ok;
    if (ok) return;
    await db.query('DROP COLLATION nocase', []);
  }
  throw new Error('This PostgreSQL server has no ICU support for case-insensitive collations');
}

export async function all<T = any>(db: DB, sql: string, params: Params = []): Promise<T[]> {
  return (await db.query(toPg(sql), args(params))).rows as T[];
}

export async function get<T = any>(db: DB, sql: string, params: Params = []): Promise<T | undefined> {
  return (await all<T>(db, sql, params))[0];
}

/** Runs a write. INSERTs return the new row's id as lastId. */
export async function run(db: DB, sql: string, params: Params = []) {
  let text = toPg(sql);
  const isInsert = /^\s*INSERT\b/i.test(text) && !/\bRETURNING\b/i.test(text);
  if (isInsert) text += ' RETURNING *';
  const r = await db.query(text, args(params));
  return { changes: r.rowCount, lastId: Number(r.rows[0]?.id ?? 0) };
}

/**
 * Inserts many rows with one statement per chunk and returns the new ids in input order.
 * One round trip per 500 rows keeps bulk imports fast against a remote database.
 */
export async function insertMany(db: DB, table: string, cols: string[], rows: unknown[][], opts: { returning?: boolean; onConflictDoNothing?: boolean; chunk?: number } = {}) {
  const ids: number[] = [];
  const size = opts.chunk ?? Math.max(1, Math.min(500, Math.floor(60000 / Math.max(1, cols.length))));
  for (let i = 0; i < rows.length; i += size) {
    const part = rows.slice(i, i + size);
    const values = part.map(() => `(${cols.map(() => '?').join(', ')})`).join(', ');
    const sql = `INSERT INTO ${table} (${cols.join(', ')}) VALUES ${values}${opts.onConflictDoNothing ? ' ON CONFLICT DO NOTHING' : ''}${opts.returning ? ' RETURNING id' : ''}`;
    const r = await db.query(toPg(sql), args(part.flat()));
    if (opts.returning) ids.push(...r.rows.map((x) => Number(x.id)));
  }
  return ids;
}

/** Runs fn inside one transaction; nested calls reuse the outer transaction. */
export async function tx<T>(db: DB, fn: (db: DB) => Promise<T>): Promise<T> {
  return db.inTransaction ? fn(db) : db.transaction(fn);
}

export function nowIso(): string {
  return new Date().toISOString().replace('T', ' ').slice(0, 19);
}

export function today(): string {
  return new Date().toISOString().slice(0, 10);
}
